Describe vision of probatus
ing-bank/probatus pull request #91
Opened 2021-03-09 15:08 UTC by Matgrb

2021-03-09 15:47 UTC, timvink requested changes
Some small remarks

2021-03-09 15:47 UTC, timvink commented on VISION.md
> +## The Roadmap
I would use milestones or a pinned ROADMAP issue for this, which keeps the vision to be more static.

2021-03-09 15:47 UTC, timvink commented on VISION.md
> +- Build a community of users, which use the package in day-to-day work and learn from each other, while contributing to probatus
Sound good, but could be more specific. Can we provide any more guidance on the scoping of the package other than 'tools to help analyze binary classifcation models and data used to train them' ?

2021-03-10 15:24 UTC, Matgrb commented
Implemented the comments, what do you think?

2021-03-10 18:46 UTC, timvink commented
Looks good to me, helps to give some direction & scope.

2021-03-10 18:46 UTC, timvink approved these changes

2021-03-11 08:13 UTC, merged